apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    env: production
    tier: cicd
    app: jenkins
    name: jenkins-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs
    server: 192.168.56.21
