apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  labels:
    env: production
    tier: backend
    app: pvc
    name: backend-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
