spring:
  r2dbc:
    url: r2dbc:mysql://${mysql.hostname:localhost}:3306/reservation?serverTimezone=Asia/Seoul
    username: msaportal
    password: msaportal
  cloud:
    stream:
      bindings:
        attachmentEntity-out-0: # 첨부파일 entity 정보 업데이트 하기 위한 이벤트
          destination: attachment-entity.topic # queue name
          group: attachment

# springdoc-openapi 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
