spring:
  application:
    name: reserve-request-service

server:
  port: 0

# config server actuator
management:
  endpoints:
    jmx:
      exposure:
        exclude: "*" # JMX에서 모든 엔드포인트 비활성화
    web:
      exposure:
        include: health, info
