spring:
  application:
    name: reserve-check-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

server:
  port: 0

# config server actuator
management:
  endpoints:
    access:
      default: read-only # 기본적으로 모든 엔드포인트를 읽기 전용으로 설정
    jmx:
      exposure:
        exclude: "*" # JMX에서 모든 엔드포인트 비활성화
    web:
      exposure:
        include: health, info

info:
  app:
    name: Reserve Check Service
    description: 예약시스템 기능 중 예약확인, 예약승인/취소 기능을 제공
