server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native,default # native file repository
  cloud:
    config:
      server:
        native:
          search-locations: file:./config
#          search-locations: ${search.location:file:///${user.home}/workspace.edu/egovframe-msa-edu/config} # Windows
#           search-locations: file://${user.home}/workspace.edu/egovframe-msa-edu/config # MacOS
  rabbitmq:
    host: ${rabbitmq.hostname:localhost}
    port: 5672
    username: guest
    password: guest

# config server actuator
management:
  endpoints:
    access:
      default: read-only # 기본적으로 모든 엔드포인트를 읽기 전용으로 설정
    jmx:
      exposure:
        exclude: "*" # JMX에서 모든 엔드포인트 비활성화
    web:
      exposure:
        include: health, info
