apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/environment: production
    app.kubernetes.io/version: "3.8.9"  # RabbitMQ 버전 예시
    team: infrastructure
spec:
  rules:
    - host: <RabbitMQ 도메인> # TODO
      http:
        paths:
          - path: /
            backend:
              serviceName: rabbitmq
              servicePort: 15672
