spring:
  application:
    name: reserve-item-service

server:
  port: 0

# config server actuator
management:
  endpoints:
    jmx:
      exposure:
        exclude: "*" # JMX에서 모든 엔드포인트 비활성화
    web:
      exposure:
        include: health, info

info:
  app:
    name: Reserve Item Service
    description: 예약시스템 기능 중 예약지역, 예약물품 관리 기능을 제공
